import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { GetServerSideProps } from 'next'

import { FaCheckCircle, FaTimesCircle } from 'react-icons/fa'


type Task = {
  id: number,
  title: string,
  completed: boolean
}

type Props = {
  tasks: Task[]
}


export default function Home({ tasks }: Props) {
  return (
    <>
      <Head>
        <title>NextSSR-refresher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={styles.main}>
        <div className={styles.description}>
          {tasks?.length === 0 ? (
            <p>There are no tasks</p>
          ) : (
            tasks?.map((task) => (
            <p key={task.id} className={styles.task}>
              {task.title}

            {task.completed ? 

            // TODO: Refactor this with a more DRY approach (if it exists, I'm not sure, but I'm sure there is a better way to do this, OPEN TO SUGGESTIONS)
              (
               <span style={{color: 'green'}}> Completed <FaCheckCircle style={{color: 'green'}} aria-label='green check mark' /></span>
             ):(
               <span style={{color: 'red'}}> Not Completed <FaTimesCircle style={{color: 'red'}} aria-label='red x mark' /></span>
             )
            } 
            
            </p>


          )))}
        </div>

      </main>
    </>
  )
}


export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/todos')
  const data: Task = await res.json()

  return {
    props: {
      tasks: data
    }
  }

}